[project]
name = "Livt.Bus"
version = "0.3.0"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "Axi4LiteMasterTest",
    "Axi4LiteTestMasterTest",
    "Axi4LiteWriteResponseTimeoutTest",
    "Axi4LiteReadAddressTimeoutTest",
    "Axi4LiteReadDataTimeoutTest",
    "AvalonMasterTest",
    "AvalonTestMasterTest",
    "WishboneMasterTest",
    "WishboneTestMasterTest",
    "Axi4LiteToWishboneBridgeTest",
    "Axi4LiteToAvalonBridgeTest",
    "AvalonToAxi4LiteBridgeTest",
    "AvalonToWishboneBridgeTest",
    "WishboneToAxi4LiteBridgeTest",
    "WishboneToAvalonBridgeTest"
]

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]
